//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteDatSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatSan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DatSan()
        {
            this.ChiTiet_DatSan = new HashSet<ChiTiet_DatSan>();
        }
    
        public int MaDat { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public Nullable<double> SoTien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTiet_DatSan> ChiTiet_DatSan { get; set; }
    }
}
