//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteDatSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class San
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public San()
        {
            this.ChiTiet_DatSan = new HashSet<ChiTiet_DatSan>();
        }
    
        public int MaSan { get; set; }
        public int MaLoaiSan { get; set; }
        public string TenSan { get; set; }
        public string DIaChi { get; set; }
        public Nullable<decimal> GIaTien { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public string HinhAnh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTiet_DatSan> ChiTiet_DatSan { get; set; }
        public virtual LoaiSan LoaiSan { get; set; }
    }
}
